# Generated by Django 2.2.5 on 2019-09-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('iduser', models.AutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=254)),
                ('email_user', models.CharField(max_length=254)),
            ],
        ),
    ]
