# Generated by Django 2.2.5 on 2019-09-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_user',
            field=models.CharField(default='', max_length=20),
        ),
    ]
